apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: test 
      image: nicolaka/netshoot
      command: ["/bin/bash","-c","sleep 3000"]
      volumeMounts:
        - name: vol
          mountPath: /mnt
  volumes:
    - name: vol
      hostPath:
        path: /var/lib/kubelet/plugins_registry/
