apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-argo
spec:
  selector:
    matchLabels:
      app: spark
  replicas: 2
  template:
    metadata:
      labels:
        app: spark
    spec:
      containers:
        - name: alex
          image: nginx
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: apache-spark
  name: spark-argo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: spark
