name: Spark CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy custom code
      run: |
        # Copy code from custom_folder into the source folder
        # ls -la src/
        # cp -r custom_folder/* src/
        # ls -la src/
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up Spark environment
      run: |
        # Install Spark and dependencies here
        # You can use Apache Spark's official Docker image or install it manually
        docker images
        docker pull apache/spark
        docker images
        # Example: Download and install Spark manually

    - name: Build and test Spark app
      run: |
        # Build and test your Spark application here
        # Example: sbt clean package
  update-manifest-argocd:
    needs: test
    runs-on: ubuntu-latest
    steps:
    
    # - name: Deploy to ArgoCD
    #   run: |
    #     # Use ArgoCD CLI or API to trigger deployment
    #     # Example: argocd app sync my-spark-app
    #     curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
    #     sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
    #     rm argocd-linux-amd64
    #     argocd login 54.226.25.98:31218 --username admin --password SojWh5-NBGRCy69G --insecure
    #     argocd app list
    #     argocd app sync spark

    - name: changing the deployment of git repo
      uses: actions/checkout@v3
      with:
        repository: 'htech7x/spark-k8s-deploy'
        token: ${{ secrets.GIT_TOKEN }}
    
    - name: setup git config
      run: |
        git config --global user.email htech7x@gmail.com
        git config --global user.name htech7x
        ls -la
        cat statefulset-master.yaml
        cat statefulset-worker.yaml
      
        echo "XXXXXXXXXX"
        echo ${{ github.run_number }}
        echo "=========="
          
        sed -i 's/spark-master-rev.*/spark-master-rev-${{ github.run_number }}/g' statefulset-master.yaml
        sed -i 's/spark-worker-rev.*/spark-worker-rev-${{ github.run_number }}/g' statefulset-worker.yaml
        
        cat statefulset-master.yaml
        echo "=========="
        cat statefulset-worker.yaml

        echo "XXXXXXXXXX"
        git add .
        git commit -m 'Done  by Github Actions Job change manifest: ${{ github.run_number }}'
        git push origin main








      
        
